section .text
global PIANO_MAIN
global PIANO_DESTROY
;Row-40 Column-0 (initial).
;Under 5 modules dedicated to maintain interactive UI.
PIANO_MAIN:
PIANO_DRAW:
	MOV EBX,0xB8CA0
	MOV EDX,0x9000
	PUSH EBX
	MOV CX,40
PIANO_LOOP:
	MOV WORD [EBX],'0' | (0x03 << 8)
	INC EBX
	LOOP PIANO_LOOP
	MOV DWORD [EDX],EBX ;Store last point in fixed area.
	POP EBX
	MOV CX,40
PIANO_SHL:;Borders of piano.
	MOV WORD [EBX],'0' | (0x03 << 8)
	ADD EBX,160
	LOOP PIANO_SHL
	MOV CX,40
	MOV DWORD EBX,[EDX]
PIANO_SHR:
	MOV WORD [EBX],'0' | (0x03 << 8)
	ADD EBX,160
	LOOP PIANO_SHR
CONTINUE:;Starting of filling algorithm.
	MOV CX,40
	MOV EBX,0xB8CAA
	PUSH EBX
PIANO_BUTTONS:
	CALL BUTTON_BORDER
	POP EBX
	LOOP PIANO_BUTTONS
	RET
PIANO_DESTROY:
	PUSHFD
	MOV EDI,0xB8CA0
	MOV AX,0x33
	MOV CX,0x2D0
	CLD
	REP STOSB
	POPFD
	RET
BUTTON_BORDER:
	MOV WORD [EBX],'0' | (0x03 << 8)
	ADD EBX,160
	LOOP BUTTON_BORDER
	ADD ESP,4
	RET
