global PUT_STRING
extern Beep
%define VMEM 0xB8000
%define SCRN_WIDTH 80
PUT_STRING:
	PUSH EBP
	MOV EBP,ESP
	MOV DWORD EDX,[EBP+8] ;Cursor x
	MOV DWORD EAX,[EBP+12] ;Cursor y
	MOV DWORD ESI,[EBP+16] ;String itself
	MOV EBX,VMEM
	FILD DWORD [EBP+12]
	MOV DWORD [EBP+12],80
	FIMUL DWORD [EBP+12]
	FISTP DWORD [EBP+12]
	MOV DWORD EAX,[EBP+12]
	ADD EAX,EDX
	ADD EBX,EAX
	PUSH EBX
@@1:
	MOV BYTE AL,[ESI]
	TEST AL,AL
	JZ @@2
	MOV BYTE [EBX],AL
	INC EBX
	MOV BYTE [EBX],0x9F
	INC EBX
	INC ESI
	JMP @@1
@@2:
	POP EAX ;EBX
	POP EBP
	RET
